FROM node:24-alpine

RUN mkdir -p /home/node/dist/app

WORKDIR /home/node/dist/app

COPY . .

RUN npm i
RUN npm run build

WORKDIR /home/node/dist/app/services/server

RUN npm run build

EXPOSE ${PORT}
RUN mkdir -p dist/app/services/server/temp && chown -R node:node /home/node
USER node
CMD npm run migration:up && npm start
