export enum PaykillaEventTypes {
  INVOICE_CREATE_INVOICE = "INVOICE_CREATE_INVOICE",
  INVOICE_CREATE_UNLIMITED_INVOICE = "INVOICE_CREATE_UNLIMITED_INVOICE",
  INVOICE_FUNDS_RECEIVED_FOR_INVOICE = "INVOICE_FUNDS_RECEIVED_FOR_INVOICE",
  INVOICE_TRANSLATION_TO_ACCOUNT_COMPLETED = "INVOICE_TRANSLATION_TO_ACCOUNT_COMPLETED",
  INVOICE_PENDING_INTERVENTION = "INVOICE_PENDING_INTERVENTION",
  INVOICE_EXPIRED = "INVOICE_EXPIRED",
  INVOICE_PAID = "INVOICE_PAID",
  INVOICE_MEMPOOL_FOUND = "INVOICE_MEMPOOL_FOUND",
  INVOICE_PENDING_COMPLIANCE = "INVOICE_PENDING_COMPLIANCE",
  INVOICE_COMPLIANCE_DECLINED = "INVOICE_COMPLIANCE_DECLINED",
}
