import { Migration } from "@mikro-orm/migrations";

import { simpleFormatting } from "../utils/lexical";
import { ns } from "@framework/constants";

import {
  ASSET_DECLINED_1,
  ASSET_DECLINED_2,
  ASSET_FINALIZED_1,
  ASSET_FINALIZED_2,
  ASSET_FINALIZED_3,
  ASSET_FINALIZED_4,
  ASSET_FINALIZED_5,
  ASSET_FINALIZED_6,
  ASSET_NEW_1,
  ASSET_NEW_2,
  ASSET_NEW_3,
  SHOWROOM_1,
  SHOWROOM_2,
  SHOWROOM_3,
} from "../utils/uuid";

export class SeedArtworkTable1738237076055 extends Migration {
  // eslint-disable-next-line @typescript-eslint/require-await
  public async up(): Promise<void> {
    this.addSql(`
      insert into ${ns}.artwork (
        id,
        title,
        description,
        image_url,
        price,
        is_copyright,
        artwork_created_at,
        artist_name,
        artwork_type,
        artwork_status,
        category,
        subject,
        style,
        material,
        dimensions_orientation,
        dimensions_height,
        dimensions_width,
        dimensions_depth,
        dimensions_units,
        showroom_id,
        token_id
      ) values (
        '${ASSET_FINALIZED_1}',
        'My First Artwork',
        '${simpleFormatting}',
        'https://www.saatchiart.com/saatchi-general/homepage/hybrid-2021/hp-hero-slide1-01272025-large.jpg',
        10000,
        false,
        null,
        null,
        'PHYSICAL',
        'APPROVED',
        'PAINTINGS',
        'ABSTRACT',
        'EXISTENTIALISM',
        'OIL_ON_CANVAS',
        'SQUARE',
        10,
        10,
        10,
        'CM',
        '${SHOWROOM_1}',
        1
      ), (
        '${ASSET_FINALIZED_2}',
        'My Second Artwork',
        '${simpleFormatting}',
        'https://www.saatchiart.com/saatchi-general/homepage/hybrid-2021/hp-hero-slide1-01272025-large.jpg',
        10000,
        false,
        null,
        null,
        'PHYSICAL',
        'APPROVED',
        'PAINTINGS',
        'ABSTRACT',
        'EXISTENTIALISM',
        'OIL_ON_CANVAS',
        'SQUARE',
        10,
        10,
        10,
        'CM',
        '${SHOWROOM_1}',
        null
      ), (
        '${ASSET_FINALIZED_3}',
        'My Third Artwork',
        '${simpleFormatting}',
        'https://www.saatchiart.com/saatchi-general/homepage/hybrid-2021/hp-hero-slide1-01272025-large.jpg',
        10000,
        false,
        null,
        null,
        'PHYSICAL',
        'APPROVED',
        'PAINTINGS',
        'ABSTRACT',
        'EXISTENTIALISM',
        'OIL_ON_CANVAS',
        'SQUARE',
        10,
        10,
        10,
        'INCH',
        '${SHOWROOM_1}',
        null
      ), (
        '${ASSET_FINALIZED_4}',
        'My Fourth Artwork',
        '${simpleFormatting}',
        'https://www.saatchiart.com/saatchi-general/homepage/hybrid-2021/hp-hero-slide1-01272025-large.jpg',
        10000,
        false,
        null,
        null,
        'PHYSICAL',
        'APPROVED',
        'PAINTINGS',
        'ABSTRACT',
        'EXISTENTIALISM',
        'OIL_ON_CANVAS',
        'SQUARE',
        10,
        10,
        10,
        'INCH',
        '${SHOWROOM_1}',
        null
      ), (
        '${ASSET_FINALIZED_5}',
        'My Fifth Artwork',
        '${simpleFormatting}',
        'https://www.saatchiart.com/saatchi-general/homepage/hybrid-2021/hp-hero-slide1-01272025-large.jpg',
        10000,
        false,
        null,
        null,
        'DIGITAL',
        'APPROVED',
        'PAINTINGS',
        'ABSTRACT',
        'EXISTENTIALISM',
        'OIL_ON_CANVAS',
        null,
        null,
        null,
        null,
        null,
        '${SHOWROOM_1}',
        null
      ), (
        '${ASSET_FINALIZED_6}',
        'My Sixth Artwork',
        '${simpleFormatting}',
        'https://www.saatchiart.com/saatchi-general/homepage/hybrid-2021/hp-hero-slide1-01272025-large.jpg',
        10000,
        false,
        null,
        null,
        'DIGITAL',
        'APPROVED',
        'PAINTINGS',
        'ABSTRACT',
        'EXISTENTIALISM',
        'OIL_ON_CANVAS',
        null,
        null,
        null,
        null,
        null,
        '${SHOWROOM_1}',
        null
      ), (
        '${ASSET_DECLINED_1}',
        'Artwork #A',
        '${simpleFormatting}',
        'https://www.saatchiart.com/saatchi-general/homepage/hybrid-2021/hp-hero-slide1-01272025-large.jpg',
        10000,
        false,
        null,
        null,
        'DIGITAL',
        'DECLINED',
        'PAINTINGS',
        'ABSTRACT',
        'EXISTENTIALISM',
        'OIL_ON_CANVAS',
        null,
        null,
        null,
        null,
        null,
        '${SHOWROOM_2}',
        null
      ), (
        '${ASSET_DECLINED_2}',
        'Artwork #B',
        '${simpleFormatting}',
        'https://www.saatchiart.com/saatchi-general/homepage/hybrid-2021/hp-hero-slide1-01272025-large.jpg',
        10000,
        false,
        null,
        null,
        'DIGITAL',
        'DECLINED',
        'PAINTINGS',
        'ABSTRACT',
        'EXISTENTIALISM',
        'OIL_ON_CANVAS',
        null,
        null,
        null,
        null,
        null,
        '${SHOWROOM_2}',
        null
      ), (
        '${ASSET_NEW_1}',
        'Artwork #C',
        '${simpleFormatting}',
        'https://www.saatchiart.com/saatchi-general/homepage/hybrid-2021/hp-hero-slide1-01272025-large.jpg',
        10000,
        false,
        null,
        null,
        'DIGITAL',
        'NEW',
        'PAINTINGS',
        'ABSTRACT',
        'EXISTENTIALISM',
        'OIL_ON_CANVAS',
        null,
        null,
        null,
        null,
        null,
        '${SHOWROOM_2}',
        null
      ), (
        '${ASSET_NEW_2}',
        'Artwork #D',
        '${simpleFormatting}',
        'https://www.saatchiart.com/saatchi-general/homepage/hybrid-2021/hp-hero-slide1-01272025-large.jpg',
        10000,
        false,
        null,
        null,
        'DIGITAL',
        'NEW',
        'PAINTINGS',
        'ABSTRACT',
        'EXISTENTIALISM',
        'OIL_ON_CANVAS',
        null,
        null,
        null,
        null,
        null,
        '${SHOWROOM_3}',
        null
      ), (
        '${ASSET_NEW_3}',
        'Artwork #E',
        '${simpleFormatting}',
        'https://www.saatchiart.com/saatchi-general/homepage/hybrid-2021/hp-hero-slide1-01272025-large.jpg',
        10000,
        false,
        null,
        null,
        'DIGITAL',
        'NEW',
        'PAINTINGS',
        'ABSTRACT',
        'EXISTENTIALISM',
        'OIL_ON_CANVAS',
        null,
        null,
        null,
        null,
        null,
        '${SHOWROOM_3}',
        null
      );
    `);
  }

  // eslint-disable-next-line @typescript-eslint/require-await
  public async down(): Promise<void> {
    this.addSql(`truncate table ${ns}.artwork restart identity cascade;`);
  }
}
